// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions, Firebase;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Llama esto en el main para inicializar Firebase:
Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBxKgJWA6GNHJBvjmFLS23bo4gbdIbOE4',
    appId: '1:1008661090688:web:6d42913ef728fdd2b9f165',
    messagingSenderId: '1008661090688',
    projectId: 'farmacia-be751',
    authDomain: 'farmacia-be751.firebaseapp.com',
    storageBucket: 'farmacia-be751.firebasestorage.app',
    measurementId: 'G-WF96CRJNNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2IOBt032rEXsan4zTEmwGPrgc_-gQ1Gg',
    appId: '1:1008661090688:android:b382785453d831d2b9f165',
    messagingSenderId: '1008661090688',
    projectId: 'farmacia-be751',
    storageBucket: 'farmacia-be751.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDymBVz9Tt6t5NwMt8RasLI43RHNLLhso',
    appId: '1:1008661090688:ios:0251e355a76f6b92b9f165',
    messagingSenderId: '1008661090688',
    projectId: 'farmacia-be751',
    storageBucket: 'farmacia-be751.firebasestorage.app',
    iosBundleId: 'com.example.farmacia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDymBVz9Tt6t5NwMt8RasLI43RHNLLhso',
    appId: '1:1008661090688:ios:0251e355a76f6b92b9f165',
    messagingSenderId: '1008661090688',
    projectId: 'farmacia-be751',
    storageBucket: 'farmacia-be751.firebasestorage.app',
    iosBundleId: 'com.example.farmacia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBxKgJWA6GNHJBvjmFLS23bo4gbdIbOE4',
    appId: '1:1008661090688:web:313e58ecdf83f780b9f165',
    messagingSenderId: '1008661090688',
    projectId: 'farmacia-be751',
    authDomain: 'farmacia-be751.firebaseapp.com',
    storageBucket: 'farmacia-be751.firebasestorage.app',
    measurementId: 'G-JSB6S1TSDN',
  );
}
